# Merge New features
We need to see that we can merge new features onto the training set easily

In [23]:
import pandas as pd
import sys
sys.path.append("..")
sys.path.append("../Utility")
#from colloidal_crystal_ML 
from Utility.segmentation_utils import ImageSegmenter
import Utility.features as features
import glob

In [24]:
training_image_list = glob.glob("/Users/jacobpietryga/Desktop/Academics/colloidal_crystal_ML/Images/Training/*")

df_list = []
for image in training_image_list:
    IS = ImageSegmenter(image)
    df_list.append(IS.df)

df_new = pd.concat(df_list)

[   0.  142.  284.  427.  569.  711.  853.  996. 1138. 1280.] [  0.  96. 191. 287. 382. 478. 573. 669. 764. 860.]
MAXIMA WEIGHTED/GLOBAL: 20.85347 46.134888
[   0.  142.  284.  427.  569.  711.  853.  996. 1138. 1280.] [  0.  96. 191. 287. 382. 478. 573. 669. 764. 860.]
MAXIMA WEIGHTED/GLOBAL: 17.355959 42.75345


/Users/jacobpietryga/Desktop/Academics/colloidal_crystal_ML/Testing/../Utility/segmentation_utils.py:667: RuntimeWarning: invalid value encountered in divide
  clusters['major_axis_length/minor_axis_length'] = clusters['major_axis_length']/clusters['minor_axis_length']
/Users/jacobpietryga/Desktop/Academics/colloidal_crystal_ML/Testing/../Utility/segmentation_utils.py:668: RuntimeWarning: invalid value encountered in divide
  clusters['perimeter/major_axis_length'] = clusters['perimeter']/clusters['major_axis_length']
/Users/jacobpietryga/Desktop/Academics/colloidal_crystal_ML/Testing/../Utility/segmentation_utils.py:669: RuntimeWarning: invalid value encountered in divide
  clusters['perimeter/minor_axis_length'] = clusters['perimeter']/clusters['minor_axis_length']


[   0.  142.  284.  427.  569.  711.  853.  996. 1138. 1280.] [  0.  96. 191. 287. 382. 478. 573. 669. 764. 860.]
MAXIMA WEIGHTED/GLOBAL: 26.54694 37.3938
[   0.  142.  284.  427.  569.  711.  853.  996. 1138. 1280.] [  0.  96. 191. 287. 382. 478. 573. 669. 764. 860.]
MAXIMA WEIGHTED/GLOBAL: 25.723345 43.93799
[   0.  142.  284.  427.  569.  711.  853.  996. 1138. 1280.] [  0.  96. 191. 287. 382. 478. 573. 669. 764. 860.]
MAXIMA WEIGHTED/GLOBAL: 23.377823 42.15036
[   0.  142.  284.  427.  569.  711.  853.  996. 1138. 1280.] [  0.  96. 191. 287. 382. 478. 573. 669. 764. 860.]
MAXIMA WEIGHTED/GLOBAL: 19.456165 34.762756


/Users/jacobpietryga/Desktop/Academics/colloidal_crystal_ML/Testing/../Utility/segmentation_utils.py:667: RuntimeWarning: divide by zero encountered in divide
  clusters['major_axis_length/minor_axis_length'] = clusters['major_axis_length']/clusters['minor_axis_length']


[   0.  142.  284.  427.  569.  711.  853.  996. 1138. 1280.] [  0.  96. 191. 287. 382. 478. 573. 669. 764. 860.]
MAXIMA WEIGHTED/GLOBAL: 20.723438 36.184387
[   0.  142.  284.  427.  569.  711.  853.  996. 1138. 1280.] [  0.  96. 191. 287. 382. 478. 573. 669. 764. 860.]
MAXIMA WEIGHTED/GLOBAL: 24.556824 43.3938
[   0.  142.  284.  427.  569.  711.  853.  996. 1138. 1280.] [  0.  96. 191. 287. 382. 478. 573. 669. 764. 860.]
MAXIMA WEIGHTED/GLOBAL: 26.622429 41.0
[   0.  142.  284.  427.  569.  711.  853.  996. 1138. 1280.] [  0.  96. 191. 287. 382. 478. 573. 669. 764. 860.]
MAXIMA WEIGHTED/GLOBAL: 21.47259 55.999756
[   0.  142.  284.  427.  569.  711.  853.  996. 1138. 1280.] [  0.  96. 191. 287. 382. 478. 573. 669. 764. 860.]
MAXIMA WEIGHTED/GLOBAL: 25.579012 37.772095
[   0.  142.  284.  427.  569.  711.  853.  996. 1138. 1280.] [  0.  96. 191. 287. 382. 478. 573. 669. 764. 860.]
MAXIMA WEIGHTED/GLOBAL: 23.609486 42.3938
[   0.  142.  284.  427.  569.  711.  853.  996. 1138. 1280.] 

/Users/jacobpietryga/Desktop/Academics/colloidal_crystal_ML/Testing/../Utility/segmentation_utils.py:667: RuntimeWarning: divide by zero encountered in divide
  clusters['major_axis_length/minor_axis_length'] = clusters['major_axis_length']/clusters['minor_axis_length']
/Users/jacobpietryga/Desktop/Academics/colloidal_crystal_ML/Testing/../Utility/segmentation_utils.py:669: RuntimeWarning: invalid value encountered in divide
  clusters['perimeter/minor_axis_length'] = clusters['perimeter']/clusters['minor_axis_length']


In [51]:
df_new = pd.concat(df_list)
df_training = pd.read_csv("/Users/jacobpietryga/Desktop/Academics/colloidal_crystal_ML/Results/training_data.csv")

print(len(df_training))

def row_adjust_filename(row:pd.Series):
    return row.Filename.split("/")[-1]

df_new_dup = df_new.copy()
df_new_dup["Filename"] = df_new_dup.apply(row_adjust_filename,axis=1)
df_training_dup = df_training.copy()
df_training_dup["Filename"] = df_training_dup.apply(row_adjust_filename,axis=1)

print(len(df_new))
check_dup = pd.concat([df_training_dup,df_new_dup])
check_dup = check_dup.drop(["Unnamed: 0.2","Unnamed: 0.1","Unnamed: 0","index","Labels",]
               ,axis=1)
check_dup = check_dup[["area","Filename","major_axis_length","minor_axis_length","perimeter"]]
check_dup = check_dup.round(2).drop_duplicates(subset=["perimeter","Filename","area"],keep=False)
print(len(check_dup))
df_training_dup[df_training_dup.Filename == "4 nM 8.bmp"].head(20)[["Region","equivalent_diameter"]]

1173
1175
1197


Region  equivalent_diameter
1057       1           557.063086
1058       2           513.630319
1059       3           444.062337
1060       4           442.043862
1061       5           370.957091
1062       6            53.911489
1063       7           416.121695
1064       8           601.542062
1065       9           757.864737
1066      10           286.641006
1067      11           317.187384
1068      12           337.174814
1069      13           529.807384
1070      14           676.749015
1071      15          1057.925464
1072      16           197.235131
1073      17           264.956435
1074      18           422.122799
1075      19           174.372945
1076      20           646.937864

In [52]:
df_new_dup[df_new_dup.Filename == "4 nM 8.bmp"].head(20)[["Region","equivalent_diameter"]]

Region  equivalent_diameter
0        1           557.063086
1        2           513.630319
2        3           444.062337
3        4           442.043862
4        5           370.957091
5        6            53.911489
6        7           416.121695
7        8           601.542062
8        9           757.864737
9       10           286.641006
10      11           317.187384
11      12           337.174814
12      13           529.807384
13      14           676.749015
14      15          1057.925464
15      16           197.235131
16      17           422.122799
17      18           174.372945
18      19           646.937864
19      20          1258.887206

In [57]:
# check duplication in more detail
t = df_training_dup[df_training_dup.Filename == "4 nM 8.bmp"][["Region","equivalent_diameter"]]
b = df_new_dup[df_new_dup.Filename == "4 nM 8.bmp"][["Region","equivalent_diameter"]]

pd.concat([t,b]).round(2).drop_duplicates(subset="equivalent_diameter",keep=False)

Region  equivalent_diameter
1073      17               264.96
1081      25              1019.45
1087      31               897.02
1089      33               495.46
1090      34               698.21
1091      35               800.61
1092      36               564.44
1093      37               734.19
1094      38               421.46
1095      39               426.86
1096      40               778.10
1097      41              1211.28
1098      42               507.39
1099      43               330.14
1100      44               511.45
1101      45               205.29
1102      46               251.54
1103      47               371.11
1104      48                83.25
23        24              1061.25
29        30               846.56
31        32               507.61
32        33               515.80
33        34               239.47

In [33]:
check_dup.area = check_dup.area.round(3)
check_dup[check_dup.Filename == "4 nM 3.bmp"].drop_duplicates(subset="area",keep="first")

area    Filename  major_axis_length  minor_axis_length  \
841  2117518.997  4 nM 3.bmp         714.721868         427.159899   
842  9049226.483  4 nM 3.bmp        1289.827605        1060.720791   
843   911503.904  4 nM 3.bmp         482.051024         272.497305   
844  1288280.788  4 nM 3.bmp         498.494227         355.934655   
845  1381241.024  4 nM 3.bmp         570.090895         338.679467   
846   897518.736  4 nM 3.bmp         433.270675         317.066459   
847   941119.554  4 nM 3.bmp         513.030993         282.257095   
850  1745678.054  4 nM 3.bmp         630.394954         432.264019   
851  1516979.421  4 nM 3.bmp         522.894685         415.215487   
852   559406.728  4 nM 3.bmp         319.475954         261.028374   

       perimeter  
841  2330.314604  
842  6379.115939  
843  1471.318503  
844  1558.254999  
845  1682.671494  
846  1557.256140  
847  1689.825077  
850  2391.414643  
851  1830.708030  
852  1215.113227

In [53]:
p_to_um = IS.pixels_to_um
print(IS.pixels_to_um)
import numpy as np
for ii in np.arange(4):
    print(2.574000e+03*p_to_um**ii)

9.37
2574.0
24118.379999999997
225989.22059999994
2117518.9970219997


In [40]:
for fn in df_new_dup.Filename.unique():
    print(fn,
          len(df_new_dup[df_new_dup.Filename == fn]),
          len(df_training_dup[df_training_dup.Filename == fn]))

4 nM 9.bmp 63 68
4 nM 8.bmp 34 48
39.5 hold 4.bmp 138 160
39.5 hold 5.bmp 129 136
39.5 hold 7.bmp 99 102
39.5 hold 6.bmp 59 0
39.5 hold 2.bmp 21 22
39.5 hold 3.bmp 59 78
39.5 hold 1.bmp 169 178
4 nM 10.bmp 40 0
39.5 hold 8.bmp 149 151
4 nM 1.bmp 14 14
4 nM 3.bmp 13 13
4 nM 6.bmp 56 56
4 nM 7.bmp 37 42
4 nM 5.bmp 57 70
4 nM 4.bmp 38 35
